config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
 
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products = Product.all
  end

  def new
  	@product = Product.new
  end

  def create
  	@product = Product.new(product_params)
  	if @product.save
  		respond_to do |format|
  			format.js
  		end
  	else
  		render 'new'
  	end
  end

  def edit
  end

  def show
  end

  private
  def product_params
  	params.require(:product).permit(:name, :category, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
 
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@product.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 

 <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :category %><br>
    <%= form.text_area :category %>
  </p>

  <p>
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/products/_product.html.erb
 <tr>
      <td><%= product.name %></td>
      <td><%= product.category %></td>
      <td><%= product.price %></td>
      <td><%= link_to 'Show', product_path(product) %></td>
 </tr>

app/views/products/create.js.erb
$("#new-band form").remove();
$("new-band a").show();
$("table#bands tbody").append("<%= j render 'product',product: @product %>"); 

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<h1>All Products</h1>
 
<table id="bands">
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Price</th>
    <th></th>
  </tr>

  <%= render @products %>
</table>

<div id="new-band">
	<%= link_to'New Product', new_product_path, remote: true %>
</div>

app/views/products/new.html.erb
<h1>Add New Product</h1>

<h1>New Products</h1>

<%= render 'form' %>

app/views/products/new.js.erb
$("#new-band").append("<%= j render'form', product: @product %>");

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>
<p> this file now modiefied </p>
<p> this file now modiefied 2 times </p>